name: simple_injector
description: Simple Injector DI
version: 0.1.0
author: RafaelBarbosatec<rafaelbarbosatec@gmail.com>
homepage: https://github.com/RafaelBarbosatec/simple_injector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
